# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a8e7e63819f166600f9d920303f1dc2ff75ee1637f28a373bf264bfdd0883d50d430a20cc15d2476dd4105780fda18114e3edf6697cf4b5f1a086c09bec79a4

test:
  secret_key_base: f025825423b63bafd0517a768692bda1b43ef3a7cc31cffb1169dd19d9f5045207cf9b16149e834d033fd7bda92c487cae7592351ac0da585559db6c461d22aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
